name: Deploy GH Pages

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:

    env:
      VUE_APP_TITAN_BRANCH: develop
      VUE_APP_GH_TOKEN: ${{ secrets.VUE_GH_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm intall, fetch data
      run: |
        npm install
        npm run fetchdata
    - name: npm build
      env:
        NODE_ENV: production
      run: |
        npm run build
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
